<a href="https://colab.research.google.com/github/kalkande/recsys-python/blob/main/01_recsys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
＃https://recsyslab.github.io/recsys-python/ja/chap01.html

import numpy as np
nan = np.nan
Du = np.array(
[[ 5,  3,  1],
 [ 6,  2,  1],
 [ 4,  1,  1],
 [ 8,  5, -1],
 [ 2,  4, -1],
 [ 3,  6, -1],
 [ 7,  6, -1],
 [ 4,  2, nan],
 [ 5,  1, nan],
 [ 8,  6, nan],
 [ 3,  4, nan],
 [ 4,  7, nan],
 [ 4,  4, nan]])
print('Du = \n',format(Du))

Du = 
 [[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]
 [ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


In [ ]:
print('Duの形状 =',np.shape(Du))

Duの形状 = (13, 3)


In [ ]:
print('Duの行数 = ',np.shape(Du)[0])

Duの行数 =  13


In [ ]:
print('Duの列数 = ',np.shape(Du)[1])

Duの列数 =  3


In [ ]:
#05 評価履歴の全要素数
print('Duの全要素数 = ',np.size(Du))

Duの全要素数 =  39


In [ ]:
#06 アイテム集合
I = np.arange(0, np.shape(Du)[0], 1)
print('I ={}'. format(I))

I =[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#07 アイテムの特徴ベクトルの集合
x = Du[:,0:2]
print('x = \n{}'. format(x))

x = 
[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]


In [ ]:
#08 アイテムiの特徴ベクトル
i = 0
print('x{} = {}'.format(i, x[i]))

x0 = [5. 3.]


In [ ]:
#09 評価値集合
ru = Du[:,2]
print('ru = {}'.format(ru))

ru = [ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]


In [ ]:
#10 評価値集合の形状
print('ruの形状 = {}'.format(np.shape(ru)))

ruの形状 = (13,)


In [ ]:
#11 評価値集合の全要素数
print('ruの全要素数 = {}'.format(np.size(ru)))
print('ruの全要素数 = {}'.format(np.shape(ru)[0]))

ruの全要素数 = 13
ruの全要素数 = 13


In [ ]:
#12 評価値集合の部分集合
i = 2
j = 5
print('ru{}からru{}までの評価値 = {}'.format(i, j-1, ru[i:j]))

ru2からru4までの評価値 = [ 1. -1. -1.]


In [ ]:
#13 評価値集合の要素の逆順
print('ruの逆順 = {}'.format(ru[::-1]))

ruの逆順 = [nan nan nan nan nan nan -1. -1. -1. -1.  1.  1.  1.]


In [ ]:
#14 アイテムiに対する評価値
i = 0
print('ru{} = {}'.format(i, ru[i]))

ru0 = 1.0


In [ ]:
#15 ユーザuが未評価であるか否かの判定
print('ユーザuが未評価 = {}'.format(np.isnan(ru)))

ユーザuが未評価 = [False False False False False False False  True  True  True  True  True
  True]


In [ ]:
#16 ユーザが評価済みであるか否かの判定
print('ユーザuが評価済み = {}'.format(~np.isnan(ru)))

ユーザuが評価済み = [ True  True  True  True  True  True  True False False False False False
 False]


In [ ]:
#17 ユーザuが評価済みのアイテム集合
Iu = I[~np.isnan(ru)]
print('Iu = {}'.format(Iu))

Iu = [0 1 2 3 4 5 6]


In [ ]:
#18 ユーザuが「好き」と評価したアイテム集合
Iup = I[ru==+1]
print('Iu+ = {}'.format(Iup))

Iu+ = [0 1 2]


In [ ]:
#19 ユーザuが「嫌い」と評価したアイテム集合
Iun = I[ru==-1]
print('Iu- = {}'.format(Iun))

Iu- = [3 4 5 6]


In [ ]:
#20 ユーザuが未評価のアイテム集合
Iu_not = I[np.isnan(ru)]
print('Iu_not = {}'.format(Iu_not))

Iu_not = [ 7  8  9 10 11 12]


In [ ]:
#21 訓練データ
DuL = Du[Iu]
print('DuL = \n{}'.format(DuL))

DuL = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]]


In [ ]:
#22 訓練事例数
print('|DuL| = {}'.format(np.shape(DuL)[0]))

|DuL| = 7


In [ ]:
#23 正事例数
print('|DuL+| = {}'.format( np.shape(DuL[DuL[:,2]==+1])[0] ) )

|DuL+| = 3


In [ ]:
#24 負事例数
print('|DuL-| = {}'.format( np.shape(DuL[DuL[:,2]==-1])[0] ) )

|DuL-| = 4


In [ ]:
#25 予測対象データ
DuU = Du[Iu_not]
print('DuU = \n{}'.format(DuU))

DuU = 
[[ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


In [ ]:
#26 予測対象事例数
print('|DuU| = {}'.format( np.shape(DuU)[0] ))

|DuU| = 6
