<a href="https://colab.research.google.com/github/kalkande/recsys-python/blob/main/02_recsys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pprint
import numpy as np
np.set_printoptions(precision=3)

In [ ]:
#01 評価値行列の生成
nan = np.nan
R = np.array([[nan,  4,  3,  1,  2,  nan],
     [5,  5,  4,  nan,  3,  3],
     [4, nan, 5,  3,  2,  nan],
     [nan,  3,  nan,  2,  1,  1],
     [2,  1,  2,  4,  nan,  3]])
print('R = \n{}'.format(R))

R = 
[[nan  4.  3.  1.  2. nan]
 [ 5.  5.  4. nan  3.  3.]
 [ 4. nan  5.  3.  2. nan]
 [nan  3. nan  2.  1.  1.]
 [ 2.  1.  2.  4. nan  3.]]


In [ ]:
#02 ユーザ集合
U = np.arange(0, np.shape(R)[0], 1)
print('U = {}'.format(U))

U = [0 1 2 3 4]


In [ ]:
#03 アイテム集合
I = np.arange(0, np.shape(R)[1], 1)
print('I = {}'.format(I))

I = [0 1 2 3 4 5]


In [ ]:
#04 ユーザ数
print('|U| = {}'.format(np.size(U)))

|U| = 5


In [ ]:
#05 アイテム数
print('|I| = {}'.format(np.size(I)))

|I| = 6


In [ ]:
#06 評価値
u = 0
i = 1
print('r{}{} = {}'.format(u, i, R[0,1]))

r01 = 4.0


In [ ]:
#07 評価値行列の全要素数
print('Rの全要素数 = {}'.format(np.size(R)))

Rの全要素数 = 30


In [ ]:
#08 観測されているか否かの判定
print('観測値 = \n{}'.format(~np.isnan(R)))

観測値 = 
[[False  True  True  True  True False]
 [ True  True  True False  True  True]
 [ True False  True  True  True False]
 [False  True False  True  True  True]
 [ True  True  True  True False  True]]


In [ ]:
#09 評価値行列の観測値数
print('|R| = {}'.format(np.count_nonzero(~np.isnan(R))))
print('|R| = {}'.format(np.size(~np.isnan(R)[~np.isnan(R)!=0])))

|R| = 22
|R| = 22


In [ ]:
#10 評価値行列の疎性
aR = np.count_nonzero(~np.isnan(R))
aU = np.size(U)
aI = np.size(I)
sparsity = 1 - aR / (aU*aI)
print('sparsity = {:.3f}'.format(sparsity))

sparsity = 0.267


In [ ]:
#11 ユーザuが評価済みのアイテム集合
u = 0
print('I{} = {}'.format(u, I[~np.isnan(R[u])] ))

I0 = [1 2 3 4]


In [ ]:
#12 各ユーザの評価済みアイテム集合
Iu = list()
for u in U:
  Iu.append( I[~np.isnan(R[u])] )
print('Iu = ')
pprint.pprint(Iu)

Iu=[ I[~np.isnan(R[u])] for u in U ]
print('Iu = ')
pprint.pprint(Iu)

Iu = 
[array([1, 2, 3, 4]),
 array([0, 1, 2, 4, 5]),
 array([0, 2, 3, 4]),
 array([1, 3, 4, 5]),
 array([0, 1, 2, 3, 5])]
Iu = 
[array([1, 2, 3, 4]),
 array([0, 1, 2, 4, 5]),
 array([0, 2, 3, 4]),
 array([1, 3, 4, 5]),
 array([0, 1, 2, 3, 5])]


In [ ]:
#13 ユーザuとユーザvの共通の評価済みアイテム集合
u = 0
v = 1
Iuv = np.intersect1d(Iu[u],Iu[v])
print('I{}{} = {}'.format(u, v, Iuv))

I01 = [1 2 4]


In [ ]:
#14 アイテムiを評価済みのユーザ集合
i = 0
print('U{} = {}'.format(i, U[~np.isnan(R[:,i])]))

U0 = [1 2 4]


In [ ]:
#15 各アイテムの評価済みユーザ集合
Ui = list()
for i in I:
  Ui.append(U[~np.isnan(R[:,i])])
print('Ui = ')
pprint.pprint(Ui)

Ui=[ U[~np.isnan(R[:,i])] for i in I ]
print('Ui = ')
pprint.pprint(Ui)

Ui = 
[array([1, 2, 4]),
 array([0, 1, 3, 4]),
 array([0, 1, 2, 4]),
 array([0, 2, 3, 4]),
 array([0, 1, 2, 3]),
 array([1, 3, 4])]
Ui = 
[array([1, 2, 4]),
 array([0, 1, 3, 4]),
 array([0, 1, 2, 4]),
 array([0, 2, 3, 4]),
 array([0, 1, 2, 3]),
 array([1, 3, 4])]


In [ ]:
#16 アイテムiとアイテムjの両方を評価済みのユーザ集合
i = 0
j = 4
Uij = np.intersect1d(Ui[i],Ui[j])
print('U{}{} = {}'.format(i, j, Uij))

U04 = [1 2]


In [ ]:
#17 評価値行列全体の平均評価値
print('R全体の平均評価値 = {:.3f}'.format( np.nanmean(R) ))

R全体の平均評価値 = 2.864


In [ ]:
#18 各アイテムの平均評価値
ri_mean = np.nanmean(R,axis=0)
print('ri_mean = {}'.format(ri_mean))

ri_mean = [3.667 3.25  3.5   2.5   2.    2.333]


In [ ]:
#19 各ユーザの平均評価値
ru_mean = np.nanmean(R,axis = 1)
print('ru_mean = {}'.format(ru_mean))

ru_mean = [2.5  4.   3.5  1.75 2.4 ]


In [ ]:
#20 評価値ベクトルの形状変換
print('ru_mean = \n{}'.format( np.ndarray.reshape(ru_mean,5,1) ))

ru_mean = 
[[2.5 ]
 [4.  ]
 [3.5 ]
 [1.75]
 [2.4 ]]


In [ ]:
#21 平均中心化評価値行列
R2 = np.ndarray.reshape( np.array([R[:,i] - ru_mean for i in I]),6,5).T
print('R\' = \n{}'.format(R2))

R' = 
[[  nan  1.5   0.5  -1.5  -0.5    nan]
 [ 1.    1.    0.     nan -1.   -1.  ]
 [ 0.5    nan  1.5  -0.5  -1.5    nan]
 [  nan  1.25   nan  0.25 -0.75 -0.75]
 [-0.4  -1.4  -0.4   1.6    nan  0.6 ]]
